networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - ${CASSANDRA_PORT}:9042
    environment:
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
    volumes:
      - ${CASSANDRA_DATA_PATH}:/var/lib/cassandra
    networks:
      - backend
    restart: always