networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - ${MINIO_PORT}:9000 # port for the MinIO server API
      - ${MINIO_CONSOLE_PORT}:9001 # port for the MinIO Console
    volumes:
      - ${MINIO_DATA_PATH}:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USERNAME}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=my_bucket
    command: server /data --console-address ":9001"
    networks:
      - backend
    restart: always