networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - ${MONGODB_DATA_PATH}:/data/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - backend
    restart: always